# Generated by Django 5.0.7 on 2026-06-20 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('base_path', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['-date', '-filename'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('New', 'Կարմիր Երգարան (New)'), ('Old', 'Word Songs (Old)')], db_index=True, max_length=3)),
                ('number', models.CharField(db_index=True, max_length=10)),
                ('title', models.TextField()),
                ('title_display', models.TextField(blank=True, default='')),
                ('lyrics', models.TextField(blank=True, default='')),
                ('key', models.CharField(blank=True, default='', max_length=16)),
                ('speed', models.CharField(blank=True, default='', max_length=16)),
                ('style', models.CharField(blank=True, default='', max_length=50)),
                ('song_type', models.CharField(blank=True, default='', max_length=50)),
                ('time_sig', models.CharField(blank=True, default='', max_length=16)),
                ('comments', models.TextField(blank=True, default='')),
                ('match_book', models.CharField(blank=True, default='', max_length=3)),
                ('match_number', models.CharField(blank=True, default='', max_length=10)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['book', 'number'],
                'indexes': [models.Index(fields=['book', 'number'], name='hymns_song_book_a5754f_idx'), models.Index(fields=['book', 'title'], name='hymns_song_book_582328_idx')],
                'unique_together': {('book', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ServiceSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_songs', to='hymns.service')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.song')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('songs', models.ManyToManyField(blank=True, related_name='themes', to='hymns.song')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
